
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Agent
{

    public int AgentId { get; set; }

    public string AgentCode { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string MiddleName { get; set; }

    public string AgentName { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public Nullable<int> DepartmentId { get; set; }

    public Nullable<int> AgentTypeId { get; set; }

    public Nullable<int> RegionId { get; set; }

    public Nullable<int> StateId { get; set; }

    public Nullable<bool> Registration { get; set; }

    public Nullable<bool> Approval { get; set; }

    public Nullable<bool> Admin { get; set; }

    public Nullable<bool> CfiUpdate { get; set; }

    public bool Active { get; set; }

    public Nullable<System.DateTime> DatetimeCreated { get; set; }

    public Nullable<System.DateTime> DatetimeUpdated { get; set; }

    public string StateCode { get; set; }

    public string LGACode { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<long> BusinessAssID { get; set; }

    public string NewAgentCode { get; set; }

    public Nullable<bool> Flag { get; set; }

    public Nullable<System.DateTime> LinkCreatedDate { get; set; }



    public virtual AgentType AgentType { get; set; }

    public virtual State State { get; set; }

}

}
