
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class AssetAllocation
{

    public int asset_allocation_id { get; set; }

    public Nullable<System.DateTime> date_created { get; set; }

    public Nullable<double> equity { get; set; }

    public Nullable<double> fixed_income { get; set; }

    public Nullable<double> money_market { get; set; }

    public Nullable<double> others { get; set; }

    public Nullable<int> asset_allocation_type { get; set; }



    public virtual AssetType AssetType { get; set; }

}

}
