
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class BenefitProcess
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BenefitProcess()
    {

        this.BenefitStatusLogs = new HashSet<BenefitStatusLog>();

    }


    public long Id { get; set; }

    public Nullable<int> TitleId { get; set; }

    public string FileNo { get; set; }

    public string File { get; set; }

    public string PIN { get; set; }

    public Nullable<int> PaymentTypeId { get; set; }

    public string EmployeeName { get; set; }

    public string DateReceivedStr { get; set; }

    public Nullable<System.DateTime> DateReceived { get; set; }

    public Nullable<System.DateTime> DateDisengaged { get; set; }

    public string EmployerCode { get; set; }

    public string EmployerName { get; set; }

    public string EmployeeAddress { get; set; }

    public string EmployeeAddress2 { get; set; }

    public Nullable<int> StateId { get; set; }

    public string MobilePhone { get; set; }

    public string Email { get; set; }

    public int StatusId { get; set; }

    public System.DateTime TimeStamp { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> DateEmployerRespond { get; set; }

    public Nullable<System.DateTime> DateToBPDTempCompute { get; set; }

    public Nullable<System.DateTime> DateTempReturnToPSC { get; set; }

    public Nullable<System.DateTime> DateMovedToBPDForPencom { get; set; }

    public Nullable<System.DateTime> DateMovedToPencom { get; set; }

    public Nullable<System.DateTime> DateSentToBank { get; set; }

    public Nullable<System.DateTime> DateAccountVerified { get; set; }

    public Nullable<System.DateTime> ApprovedBPDReceivedDate { get; set; }

    public Nullable<System.DateTime> DatePencomApproval { get; set; }

    public Nullable<System.DateTime> DateReceiptPencomApproval { get; set; }



    public virtual BenefitClass BenefitClass { get; set; }

    public virtual State State { get; set; }

    public virtual Title Title { get; set; }

    public virtual BenefitStatu BenefitStatu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BenefitStatusLog> BenefitStatusLogs { get; set; }

}

}
