
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class BenefitStatusLog
{

    public long StatusLogId { get; set; }

    public Nullable<int> StatusId { get; set; }

    public Nullable<long> BenefitProcessId { get; set; }

    public string Comment { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }



    public virtual BenefitProcess BenefitProcess { get; set; }

}

}
