
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class BenefitApplication
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BenefitApplication()
    {

        this.EmployeeBenefitDocuments = new HashSet<EmployeeBenefitDocument>();

    }


    public string Employee_Pin { get; set; }

    public int BenefitSubClassId { get; set; }

    public Nullable<int> Status { get; set; }

    public System.DateTime DateApplied { get; set; }

    public int BenefitApplicationId { get; set; }

    public string DocumentId { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }



    public virtual Status Status1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeBenefitDocument> EmployeeBenefitDocuments { get; set; }

    public virtual Employee Employee { get; set; }

}

}
