
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class BenefitChecklistMap
{

    public long MappingId { get; set; }

    public Nullable<long> BenefitProcessId { get; set; }

    public Nullable<int> PaymentClassId { get; set; }

    public Nullable<int> DocumentId { get; set; }

    public Nullable<bool> IsUploaded { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

}

}
