
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class BenefitDifferential
{

    public long Id { get; set; }

    public string PIN { get; set; }

    public string BenefitType { get; set; }

    public Nullable<int> BenefitTypeId { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<bool> Reconcilled { get; set; }

    public string BenefitStatus { get; set; }

    public Nullable<int> BenefitStatusId { get; set; }

}

}
