
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Branding
{

    public string EmailAddress { get; set; }

    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public string Company { get; set; }

    public string Job_Title { get; set; }

    public string Phone { get; set; }

    public Nullable<double> MEMBER_RATING { get; set; }

    public string OPTIN_TIME { get; set; }

    public string OPTIN_IP { get; set; }

    public Nullable<System.DateTime> CONFIRM_TIME { get; set; }

    public string CONFIRM_IP { get; set; }

    public Nullable<double> LATITUDE { get; set; }

    public Nullable<double> LONGITUDE { get; set; }

    public Nullable<double> GMTOFF { get; set; }

    public Nullable<double> DSTOFF { get; set; }

    public string TIMEZONE { get; set; }

    public string CC { get; set; }

    public string REGION { get; set; }

    public Nullable<System.DateTime> LAST_CHANGED { get; set; }

    public Nullable<double> LEID { get; set; }

    public string EUID { get; set; }

    public string NOTES { get; set; }

    public int Id { get; set; }

    public Nullable<bool> Status { get; set; }

}

}
