
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class BVNdata
{

    public long Id { get; set; }

    public string Pin { get; set; }

    public string Bvn { get; set; }

    public string Nin { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<bool> Confimed { get; set; }

    public Nullable<System.DateTime> DateConfirmed { get; set; }

    public Nullable<System.DateTime> DateUpdated { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }



    public virtual Employee Employee { get; set; }

}

}
