
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Campaign
{

    public int Id { get; set; }

    public string PseudoId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string OtherName { get; set; }

    public string Company { get; set; }

    public string CompanyAddress { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public Nullable<int> StateName { get; set; }

    public string Address { get; set; }

    public string Todo { get; set; }

    public Nullable<System.DateTime> TodoDate { get; set; }

    public string Remarks { get; set; }

    public string Source { get; set; }

    public string Agent { get; set; }

    public Nullable<System.DateTime> Dob { get; set; }

    public Nullable<System.DateTime> DateUploaded { get; set; }

    public string UploadGroup { get; set; }

}

}
