
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class CaseAttachment
{

    public int Id { get; set; }

    public string AttachmentName { get; set; }

    public string Description { get; set; }

    public Nullable<int> CaseId { get; set; }

    public byte[] Attachment { get; set; }



    public virtual Case Case { get; set; }

}

}
