
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class CaseSummary
{

    public int CaseSummaryId { get; set; }

    public System.DateTime DateCreated { get; set; }

    public string Summary { get; set; }

    public string Description { get; set; }

    public string CurrentStatus { get; set; }

    public string CaseNumber { get; set; }

    public string PIN { get; set; }

    public System.DateTime LastUpdated { get; set; }

    public string CaseType { get; set; }

    public string CLosedBy { get; set; }

    public string AssignedTo { get; set; }

    public bool IswebGenerated { get; set; }

}

}
