
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class CFIBiometric
{

    public int CFIBiometricId { get; set; }

    public int UserId { get; set; }

    public string Passport { get; set; }

    public string ContributorSignature { get; set; }

    public string CongentForm { get; set; }

    public string PFASignature { get; set; }

    public bool Active { get; set; }

    public string DataSrc { get; set; }

    public Nullable<bool> SentToPencom { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public System.DateTime DatetimeCreated { get; set; }

    public System.DateTime DatetimeUpdated { get; set; }

    public bool ConsentAccepted { get; set; }



    public virtual CFIRegisterUser CFIRegisterUser { get; set; }

}

}
