
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class CFIEmploymentDetail
{

    public int EmploymentDetailId { get; set; }

    public int UserId { get; set; }

    public Nullable<int> SectorId { get; set; }

    public Nullable<bool> IsEmployerIPPIS { get; set; }

    public string EmployerCode { get; set; }

    public string NatureofBusiness { get; set; }

    public string EmployerName { get; set; }

    public string OfficeName { get; set; }

    public string OfficeStreetName { get; set; }

    public string OfficeStateCode { get; set; }

    public string OfficeLGACode { get; set; }

    public Nullable<bool> IsNigerian { get; set; }

    public string Building { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string LocalGovernmentCode { get; set; }

    public string StateCode { get; set; }

    public string CountryCode { get; set; }

    public string ZIP { get; set; }

    public string POBox { get; set; }

    public string PhoneNo { get; set; }

    public string MobileNo { get; set; }

    public string EmployeeId { get; set; }

    public Nullable<int> ServiceIdNo { get; set; }

    public string Designation { get; set; }

    public string DateOfFirstAppointmentX { get; set; }

    public string DateOfCurrentAppointmentX { get; set; }

    public string DateOfEmployment { get; set; }

    public bool Active { get; set; }

    public Nullable<bool> SentToPencom { get; set; }

    public string DataSrc { get; set; }

    public Nullable<System.DateTime> DatetimeCreated { get; set; }

    public Nullable<System.DateTime> DatetimeUpdated { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> DateOfFirstAppointment { get; set; }

    public Nullable<System.DateTime> DateOfCurrentAppointment { get; set; }



    public virtual CFIRegisterUser CFIRegisterUser { get; set; }

    public virtual Sector Sector { get; set; }

}

}
