
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class CFISupportDocument
{

    public int SupportDocId { get; set; }

    public int UserId { get; set; }

    public int DocumentId { get; set; }

    public string Pin { get; set; }

    public string DocumentName { get; set; }

    public string DataSrc { get; set; }

    public System.DateTime DatetimeCreated { get; set; }

    public System.DateTime DatetimeUpdated { get; set; }



    public virtual ECRSPrivatePublicSector ECRSPrivatePublicSector { get; set; }

    public virtual CFIDocument CFIDocument { get; set; }

}

}
