
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ChangeOfNameProfile
{

    public int Id { get; set; }

    public string Pin { get; set; }

    public string OldName { get; set; }

    public string NewName { get; set; }

    public string Doc1 { get; set; }

    public string Doc2 { get; set; }

    public string Ext1 { get; set; }

    public string Ext2 { get; set; }

    public string DocumentId { get; set; }

    public Nullable<System.DateTime> DateUploaded { get; set; }

    public string Status { get; set; }

    public string Description { get; set; }

    public string OldFirstName { get; set; }

    public string NewFirstName { get; set; }

    public string OldMiddleName { get; set; }

    public string NewMiddleName { get; set; }

    public string Reason { get; set; }



    public virtual Employee Employee { get; set; }

}

}
