
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ClientUpdate
{

    public int Id { get; set; }

    public string Pin { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public System.DateTime DateCreated { get; set; }

    public bool Status { get; set; }

}

}
