
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class cnssl2
{

    public Nullable<double> F1 { get; set; }

    public string PIN { get; set; }

    public string SURNAME { get; set; }

    public string FIRSTNAME { get; set; }

    public string OTHERNAMES { get; set; }

    public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }

    public string EMPLOYER_NAME { get; set; }

    public string EMPLOYER_ADDRESS { get; set; }

    public string MOBILE_PHONE { get; set; }

    public string EMAIL { get; set; }

    public string CORRESPONDENCE_ADDS { get; set; }

    public Nullable<System.DateTime> VALUE_DATE { get; set; }

    public string NARRATION { get; set; }

    public Nullable<double> EE { get; set; }

    public Nullable<double> ER { get; set; }

    public Nullable<double> AVC { get; set; }

    public Nullable<double> WITHDRAWAL { get; set; }

    public Nullable<double> WITHDRAWAL_VC { get; set; }

    public Nullable<bool> Status { get; set; }

    public int Id { get; set; }

}

}
