
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class CONTRI
{

    public string EMPLOYER_CODE { get; set; }

    public string Pin { get; set; }

    public Nullable<decimal> Employee_Contribution { get; set; }

    public Nullable<decimal> Employer_Contribution { get; set; }

    public Nullable<System.DateTime> Contribution_Date { get; set; }

    public Nullable<decimal> Other_Contribution { get; set; }

    public Nullable<decimal> Employee_Fee { get; set; }

    public Nullable<decimal> Employer_Fee { get; set; }

    public Nullable<decimal> Other_Fee { get; set; }

    public Nullable<decimal> Total_Units { get; set; }

    public Nullable<decimal> Total_Contribution { get; set; }

    public Nullable<decimal> Total_Fee { get; set; }

    public Nullable<decimal> Employee_Bf { get; set; }

    public Nullable<decimal> Employer_Bf { get; set; }

    public Nullable<System.DateTime> Payment_Date { get; set; }

    public Nullable<System.DateTime> Trans_Date { get; set; }

    public Nullable<decimal> Scheme_Id { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<decimal> Trans_Units_R { get; set; }

    public Nullable<decimal> Trans_Units_V { get; set; }

    public Nullable<System.DateTime> Value_Date { get; set; }

    public decimal Trans_Id { get; set; }

    public Nullable<decimal> Vat_Fee { get; set; }

    public Nullable<byte> Flaguploaded { get; set; }

    public Nullable<decimal> Fund_Id { get; set; }

    public Nullable<decimal> Reconciliation_Transid { get; set; }

    public Nullable<decimal> Withdrawal { get; set; }

    public Nullable<decimal> Withdrawal_Vc { get; set; }

    public string BATCH_ID { get; set; }

}

}
