
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ContributionBatch
{

    public string BATCH_ID { get; set; }

    public Nullable<decimal> USERID { get; set; }

    public Nullable<System.DateTime> CREATED { get; set; }

    public string DESCRIPTION { get; set; }

    public string CHECKED { get; set; }

    public Nullable<decimal> CHECKED_BY { get; set; }

    public Nullable<System.DateTime> CHECKED_DATE { get; set; }

    public string NARRATION { get; set; }

    public Nullable<decimal> SCHEME_ID { get; set; }

    public Nullable<System.DateTime> CLEARED_DATE { get; set; }

    public string BATCH_TYPE { get; set; }

    public Nullable<decimal> FEECODE { get; set; }

    public string BRANCH_CODE { get; set; }

    public string PFA_CODE { get; set; }

    public string PFC_CODE { get; set; }

    public string OLD_PFACODE { get; set; }

    public string EMPLOYER_CODE { get; set; }

    public Nullable<decimal> SCHEDULE_ID { get; set; }

    public Nullable<decimal> CONT_AMOUNT { get; set; }

    public string TXN { get; set; }

    public Nullable<int> SNO { get; set; }

    public string CONTRIBUTION_TYPE { get; set; }

    public Nullable<decimal> ID { get; set; }

    public string REFNO { get; set; }

    public string FILE_NAME { get; set; }

    public string LOCKED { get; set; }

    public int PK { get; set; }

}

}
