
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class CONTRIBUTION1
{

    public string BATCH_ID { get; set; }

    public string PIN { get; set; }

    public Nullable<decimal> EMPLOYEE_CONTRIBUTION { get; set; }

    public Nullable<decimal> EMPLOYER_CONTRIBUTION { get; set; }

    public Nullable<System.DateTime> CONTRIBUTION_DATE { get; set; }

    public string POSTED { get; set; }

    public Nullable<decimal> OTHER_CONTRIBUTION { get; set; }

    public string EMPLOYEE_VARIANCE { get; set; }

    public string EMPLOYER_VARIANCE { get; set; }

    public string OTHER_VARIANCE { get; set; }

    public Nullable<decimal> EMPLOYEE_FEE { get; set; }

    public Nullable<decimal> EMPLOYER_FEE { get; set; }

    public Nullable<decimal> OTHER_FEE { get; set; }

    public Nullable<decimal> TOTAL_UNITS { get; set; }

    public Nullable<decimal> TOTAL_CONTRIBUTION { get; set; }

    public Nullable<decimal> TOTAL_FEE { get; set; }

    public Nullable<decimal> EMPLOYEE_BF { get; set; }

    public Nullable<decimal> EMPLOYER_BF { get; set; }

    public string EMPLOYER_CODE { get; set; }

    public Nullable<System.DateTime> PAYMENT_DATE { get; set; }

    public Nullable<System.DateTime> TRANS_DATE { get; set; }

    public Nullable<decimal> SCHEME_ID { get; set; }

    public Nullable<decimal> WITHDRAWAL { get; set; }

    public Nullable<decimal> PAYMENT_ID { get; set; }

    public Nullable<decimal> WITHDRAWAL_VC { get; set; }

    public Nullable<decimal> PRICE { get; set; }

    public Nullable<decimal> TRANS_UNITS_R { get; set; }

    public Nullable<decimal> TRANS_UNITS_V { get; set; }

    public Nullable<decimal> WITHDRAWAL_AMT { get; set; }

    public string TRANS_TYPE { get; set; }

    public Nullable<decimal> EE_LEGACY { get; set; }

    public Nullable<decimal> ER_LEGACY { get; set; }

    public Nullable<System.DateTime> VALUE_DATE { get; set; }

    public decimal TRANS_ID { get; set; }

    public Nullable<decimal> VAT_FEE { get; set; }

    public Nullable<byte> FLAGUPLOADED { get; set; }

    public Nullable<decimal> FUND_ID { get; set; }

    public string RETIREE_DEPOSITE { get; set; }

    public string BRANCH_CODE { get; set; }

    public string OLD_PFACODE { get; set; }

    public string PFC_CODE { get; set; }

    public string PFA_CODE { get; set; }

    public Nullable<decimal> POSTED_BY { get; set; }

    public Nullable<System.DateTime> POSTED_DATE { get; set; }

    public Nullable<decimal> RECONCILIATION_TRANSID { get; set; }

    public Nullable<decimal> FEE_ID { get; set; }

    public string CHECKED { get; set; }

    public string NARRATION { get; set; }

}

}
