
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Contact
{

    public int Id { get; set; }

    public string Region { get; set; }

    public string Branch { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Lat { get; set; }

    public string Long { get; set; }

    public bool IsTransferCenter { get; set; }

    public Nullable<int> GroupId { get; set; }

    public string BranchState { get; set; }

}

}
