
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class DigitalSubscription
{

    public int ID { get; set; }

    public string Pin { get; set; }

    public bool HardCopyStatement { get; set; }

    public bool NoStatementNoAlert { get; set; }

    public bool TransactionSMS { get; set; }

    public bool DigitalStatement { get; set; }

    public bool EventNofication { get; set; }

    public bool NewsLetters { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

    public Nullable<System.DateTime> DateUpdated { get; set; }

}

}
