
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ECRSResponse
{

    public int ID { get; set; }

    public string SetId { get; set; }

    public Nullable<int> Sn { get; set; }

    public string PFA { get; set; }

    public string Surname { get; set; }

    public string Firstname { get; set; }

    public string Middlename { get; set; }

    public string Remarks { get; set; }

    public string RecaptureStatus { get; set; }

    public string Gender { get; set; }

    public string BVN { get; set; }

    public string NIN { get; set; }

    public string Email { get; set; }

    public string PhoneNo { get; set; }

    public string Employer { get; set; }

    public Nullable<System.DateTime> UploadDate { get; set; }

    public Nullable<bool> SMSSent { get; set; }

    public Nullable<System.DateTime> DateSMSent { get; set; }

    public string ResponseCode { get; set; }

    public string ResponseMessage { get; set; }

    public string ResponseObj { get; set; }

}

}
