
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ECRSContributor
{

    public string S_n { get; set; }

    public string RSA_PIN { get; set; }

    public string Set_ID { get; set; }

    public string Sno { get; set; }

    public string PFA_Code { get; set; }

    public string Registration_Type { get; set; }

    public string Temporary_PIN { get; set; }

    public string Title { get; set; }

    public string Surname { get; set; }

    public string Firstname { get; set; }

    public string Middlename { get; set; }

    public string Column_11 { get; set; }

    public string Gender { get; set; }

    public string Marital_Status { get; set; }

    public string Nationality { get; set; }

    public string Origin_State { get; set; }

    public string Origin_LGA { get; set; }

    public Nullable<System.DateTime> Date_of_Birth { get; set; }

    public string Place_of_Birth { get; set; }

    public string BVN { get; set; }

    public string NIN { get; set; }

    public string Intnl_Passport__ { get; set; }

    public string Nigeria_Abroad { get; set; }

    public string Residence_House__ { get; set; }

    public string Residence_Street_Name { get; set; }

    public string Residence_Town_City { get; set; }

    public string P_O_Box { get; set; }

    public string Residence_LGA { get; set; }

    public string Residence_State { get; set; }

    public string ResidenceCountryCode { get; set; }

    public string Residence_ZIP { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Employer_Sector { get; set; }

    public string Employer_Code { get; set; }

    public string Employer_Name { get; set; }

    public string Nature_of_Business { get; set; }

    public string Employer_Phone { get; set; }

    public string First_Appointment_Date { get; set; }

    public Nullable<System.DateTime> Current_Employment_Date { get; set; }

    public string Employer_Nigeria_Abroad { get; set; }

    public string Employer_Building_Name__ { get; set; }

    public string Employer_Street { get; set; }

    public string Employer_Town_City { get; set; }

    public string Employer_P_O_Box { get; set; }

    public string Employer_LGA { get; set; }

    public string Employer_State { get; set; }

    public string Employer_Country { get; set; }

    public string Employer_ZIP { get; set; }

    public string NOK_Relationship { get; set; }

    public string NOK_Title { get; set; }

    public string NOK_Surname { get; set; }

    public string NOK_Firstname { get; set; }

    public string NOK_Middlename { get; set; }

    public string NOK_Gender { get; set; }

    public string NOK_Email { get; set; }

    public string NOK_Phone { get; set; }

    public string NOK_Nigeria_Abroad { get; set; }

    public string NOK_Residence_House { get; set; }

    public string NOK_Residence_Street { get; set; }

    public string NOK_Residence_Town { get; set; }

    public string NOK_P_O_Box { get; set; }

    public string NOK_Residence_LGA { get; set; }

    public string NOK_Residence_State { get; set; }

    public string NOK_Country { get; set; }

    public string NOK_Zip_Code { get; set; }

    public string Date_of_Registration { get; set; }

    public string Remarks { get; set; }

    public Nullable<System.DateTime> Date_Created { get; set; }

    public string Status { get; set; }

    public string DateCreated2 { get; set; }

}

}
