
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EmailRepository
{

    public decimal Id { get; set; }

    public string Pin { get; set; }

    public string email { get; set; }

    public bool IsSent { get; set; }

    public Nullable<bool> IsValidated { get; set; }

    public string ValidationStatus { get; set; }

    public Nullable<System.DateTime> DateValidated { get; set; }

    public System.DateTime DateCreated { get; set; }

    public string Token { get; set; }

}

}
