
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EmailLog
{

    public long LogId { get; set; }

    public Nullable<long> BatchId { get; set; }

    public string PIN { get; set; }

    public string Status { get; set; }

    public string Error { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

}

}
