
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EMP
{

    public int Id { get; set; }

    public Nullable<bool> SMSStatus { get; set; }

    public Nullable<bool> EmailStatus { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string PIN { get; set; }

    public string FirstName { get; set; }

}

}
