
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeClean
{

    public string REGISTRATION_CODE { get; set; }

    public string PIN { get; set; }

    public string TITLE { get; set; }

    public string SURNAME { get; set; }

    public string FIRSTNAME { get; set; }

    public string OTHERNAMES { get; set; }

    public string MOBILE_PHONE { get; set; }

    public string EMAIL { get; set; }

    public string employer_name { get; set; }

    public string EMPLOYER_RCNO { get; set; }

    public string EMPLOYER_ADDRESS { get; set; }

    public string EMPLOYER_ADDRESS1 { get; set; }

    public string EMPLOYER_STATECODE { get; set; }

    public string TITLE_NEW { get; set; }

    public string SURNAME_NEW { get; set; }

    public string FIRSTNAME_NEW { get; set; }

    public string OTHERNAMES_NEW { get; set; }

    public string MOBILE_PHONE_NEW { get; set; }

    public string EMAIL_NEW { get; set; }

    public string employer_name_NEW { get; set; }

    public string EMPLOYER_RCNO_NEW { get; set; }

    public string EMPLOYER_ADDRESS_NEW { get; set; }

    public string EMPLOYER_ADDRESS1_NEW { get; set; }

    public string EMPLOYER_STATECODE_NEW { get; set; }

    public string ACCOUNT_OFFICER { get; set; }

    public Nullable<int> RM_CODE { get; set; }

    public string RM_EMAIL { get; set; }

    public string MODIFIED_BY { get; set; }

    public Nullable<System.DateTime> MODIFIED_ON { get; set; }

}

}
