
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeBiometric
{

    public decimal Id { get; set; }

    public Nullable<int> UserId { get; set; }

    public string Pin { get; set; }

    public string Passport { get; set; }

    public string Signature { get; set; }

    public string ConsentForm { get; set; }

    public Nullable<bool> Converted { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

    public string ModifiedBy { get; set; }

}

}
