
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeBenefitDocument
{

    public int Id { get; set; }

    public string Filename { get; set; }

    public Nullable<System.DateTime> DateUploaded { get; set; }

    public Nullable<int> BenefitApplicationId { get; set; }

    public string ext { get; set; }



    public virtual BenefitApplication BenefitApplication { get; set; }

}

}
