
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EmployerDetail
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EmployerDetail()
    {

        this.Employees = new HashSet<Employee>();

    }


    public string Recno { get; set; }

    public string EmployerName { get; set; }

    public string Address { get; set; }

    public Nullable<decimal> ID { get; set; }

    public string ContactPerson { get; set; }

    public string Email { get; set; }

    public string MobilePhone { get; set; }

    public string OldEmployerCode { get; set; }

    public long TransId { get; set; }

    public bool Active { get; set; }

    public string SectorCode { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Employee> Employees { get; set; }

}

}
