
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeProfileUpdate
{

    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string MiddleName { get; set; }

    public Nullable<System.DateTime> Dob { get; set; }

    public string State { get; set; }

    public string Nationality { get; set; }

    public string Gender { get; set; }

    public string Email { get; set; }

    public string Telephone { get; set; }

    public string HomePhone { get; set; }

    public string MaritalStatus { get; set; }

    public string Children { get; set; }

    public string NextofKinName { get; set; }

    public string Relationship { get; set; }

    public string NokAddress { get; set; }

    public string NokPhone { get; set; }

    public string Education { get; set; }

    public string Employment { get; set; }

    public string AccountNumber { get; set; }

    public string Bank { get; set; }

    public string AccountName { get; set; }

    public string Declaration { get; set; }

    public string Address { get; set; }

    public string MedicalConditions { get; set; }

    public string BloodGroup { get; set; }

    public string Genotype { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string PermanentAddress { get; set; }

    public string Spouse { get; set; }

}

}
