
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeChildren
{

    public int Id { get; set; }

    public Nullable<int> EmployeeId { get; set; }

    public string ChildName { get; set; }

    public Nullable<System.DateTime> Dob { get; set; }

}

}
