
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ExitProcessMaster
{

    public string PIN { get; set; }

    public Nullable<decimal> MIN_LUMPSUM { get; set; }

    public Nullable<decimal> MAX_LUMPSUM { get; set; }

    public Nullable<decimal> MIN_MONTHLY { get; set; }

    public Nullable<decimal> MAX_MONTHLY { get; set; }

    public Nullable<decimal> RSA_BALANCE { get; set; }

    public Nullable<decimal> LUMPSUM_COLLECTED { get; set; }

    public Nullable<decimal> CHECKED_BY { get; set; }

    public string BATCH_ID { get; set; }

    public Nullable<System.DateTime> DATE_EXITED { get; set; }

    public Nullable<decimal> ADMIN_CHARGE { get; set; }

    public Nullable<decimal> FINAL_SALARY { get; set; }

    public Nullable<System.DateTime> FIRST_PAYMENT_DATE { get; set; }

    public Nullable<System.DateTime> NEXT_PAYMENT_DATE { get; set; }

    public bool LUMPSUM_CHECKED { get; set; }

    public bool FEE_CHECKED { get; set; }

    public Nullable<int> AGE { get; set; }

    public decimal ID { get; set; }

    public Nullable<decimal> ADMINFEE_ID { get; set; }

    public bool GENERATED { get; set; }

    public bool CAN_GENERATE { get; set; }

    public Nullable<decimal> FEE_ID { get; set; }

    public Nullable<int> FREQUENCY { get; set; }

    public bool MIGRATED { get; set; }

    public string BATCHID_W { get; set; }

    public string BATCHID_D { get; set; }

    public string CLIENT_STATUS { get; set; }

    public Nullable<System.DateTime> CHECKED_DATE { get; set; }

    public Nullable<decimal> MID_LUMPSUM { get; set; }

    public Nullable<decimal> TOTAL_AMOUNT_PAID_BF { get; set; }

    public Nullable<decimal> GENERATED_BY { get; set; }

    public Nullable<System.DateTime> GENERATED_DATE { get; set; }

    public Nullable<System.DateTime> LUMPSUM_PAYMENT_DATE { get; set; }

    public string ACCOUNT_NAME { get; set; }

    public string ACCOUNT_NUMBER { get; set; }

    public string ACCOUNT_BANK { get; set; }

    public bool PRINT_SCHEDULE { get; set; }

    public bool PRINTED { get; set; }

    public bool CONTRIBUTION { get; set; }

    public string PAYMENT_TYPE { get; set; }

    public decimal ARREARS { get; set; }

    public Nullable<decimal> RSABALANCEOLD { get; set; }

    public string REMARK { get; set; }

    public string BANK_BRANCH { get; set; }

    public bool PRINTEDADVICE { get; set; }

    public bool PRINTEDINSTRUCTION { get; set; }

    public bool PRINT_INSTRUCTION { get; set; }

    public bool PRINT_ADVICE { get; set; }

    public Nullable<decimal> TRANS_UNITS { get; set; }

    public Nullable<decimal> INTERESTRATE { get; set; }

    public Nullable<decimal> PAY_YEARS1 { get; set; }

    public Nullable<decimal> PAY_YEARS { get; set; }

    public Nullable<decimal> PRICE { get; set; }

    public string PHONE { get; set; }

    public Nullable<decimal> REC_MONTHLY { get; set; }

    public Nullable<decimal> VAT { get; set; }

    public string SORT_CODE { get; set; }

    public string PENCOMSTATUS { get; set; }

    public Nullable<decimal> BASIC { get; set; }

    public Nullable<decimal> TRANSPORT { get; set; }

    public Nullable<decimal> HOUSING { get; set; }

    public Nullable<decimal> SURVIVAL { get; set; }

    public Nullable<decimal> SURVIVAL_FEE { get; set; }

    public Nullable<decimal> SURVIVAL_BALANCE { get; set; }

    public Nullable<decimal> GENERATED_LUMPSUM { get; set; }

    public Nullable<decimal> GENERATED_MONTHLY { get; set; }

    public string RMAS_GENERATED { get; set; }

    public Nullable<System.DateTime> ARREARS_DATE { get; set; }

    public Nullable<decimal> CONSOLIDATED_ALLOWANCE { get; set; }

    public Nullable<decimal> CONSOLIDATED_SALARY { get; set; }

    public Nullable<int> RETIREMENT_AGE { get; set; }

    public Nullable<decimal> ANNUITY { get; set; }

}

}
