
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ExpressionOfInterest
{

    public int id { get; set; }

    public string RsaPin { get; set; }

    public string Surname { get; set; }

    public string Firstname { get; set; }

    public string MiddleName { get; set; }

    public string EmployerName { get; set; }

    public string CurrentPfa { get; set; }

    public string Address { get; set; }

    public string Telephone1 { get; set; }

    public string Telephone2 { get; set; }

    public string Email { get; set; }

    public System.DateTime DateCreated { get; set; }

    public string EmployerAddress { get; set; }

    public string EmployerStateCode { get; set; }

    public string CurrentPFACode { get; set; }

    public string State { get; set; }

}

}
