
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Feedback
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Telephone { get; set; }

    public string Message { get; set; }

    public string EmployerCode { get; set; }

    public string FeedbackType { get; set; }

    public string Status { get; set; }

    public string Remarks { get; set; }

    public System.DateTime DateCreated { get; set; }

    public System.DateTime DateUpdated { get; set; }

    public string Createdby { get; set; }

    public string Modifiedby { get; set; }

}

}
