
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class GUIN
{

    public string EMPLOYEENUMBER { get; set; }

    public Nullable<double> ff { get; set; }

    public string C_EMPLOYEE_NAME { get; set; }

    public string Email { get; set; }

    public string Fund_Manager { get; set; }

    public string pn { get; set; }

    public string pin { get; set; }

    public int Id { get; set; }

    public Nullable<bool> Status { get; set; }

}

}
