
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ImageAdministration
{

    public int ImageAdminId { get; set; }

    public string PassportPhotograph { get; set; }

    public string Signature { get; set; }

    public string LeftThumb { get; set; }

    public string RightThumb { get; set; }

    public string LeftIndexFinger { get; set; }

    public string RightIndexFinger { get; set; }

    public string LeftMiddleFinger { get; set; }

    public string RightMiddleFinger { get; set; }

    public string LeftRingFinger { get; set; }

    public string RightRingFinger { get; set; }

    public string LeftPinkyFinger { get; set; }

    public string RightPinkyFinger { get; set; }

    public Nullable<bool> Active { get; set; }

    public string SupportDocument { get; set; }

    public string CongentForm { get; set; }

    public string RegBiometrics { get; set; }

    public string RegSupportDoc { get; set; }

}

}
