
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class MCPPayment
{

    public long PaymentId { get; set; }

    public string ClientNo { get; set; }

    public string RefNo { get; set; }

    public string PartnerName { get; set; }

    public string TransNo { get; set; }

    public string PaymentDescription { get; set; }

    public Nullable<System.DateTime> TransDate { get; set; }

    public string Status { get; set; }

    public string PartnerRefNo { get; set; }

    public string PartnerStatus { get; set; }

    public string Currency { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<decimal> AmountSettle { get; set; }

    public string Narration { get; set; }

    public string ResponseCode { get; set; }

    public string ResponseMessage { get; set; }

    public string PaymentType { get; set; }

    public string CardType { get; set; }

    public System.DateTime DateCreated { get; set; }

    public string CreatedBy { get; set; }

    public string Pin { get; set; }

    public string PhoneNo { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public string StatusCode { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public string Email { get; set; }

}

}
