
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Merchant
{

    public int Id { get; set; }

    public string MerchantCode { get; set; }

    public string MerchantName { get; set; }

    public string PrimaryIP { get; set; }

    public string SecondaryIP { get; set; }

    public string EmailAddress { get; set; }

    public string ContactPerson { get; set; }

    public string MobileNo { get; set; }

    public string OfficePhone { get; set; }

}

}
