
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class NewExpressionOfInterest
{

    public int id { get; set; }

    public string FullName { get; set; }

    public string Address { get; set; }

    public string State { get; set; }

    public string Telephone1 { get; set; }

    public string Email { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

}

}
