
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class NextOfKin
{

    public int Id { get; set; }

    public string Employee_Pin { get; set; }

    public string FirstName { get; set; }

    public string Gender { get; set; }

    public string Surname { get; set; }

    public string OtherNames { get; set; }

    public string Relation { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string StateCode { get; set; }

    public string CountryCode { get; set; }

    public string LGACode { get; set; }

    public string City { get; set; }

    public string StreetName { get; set; }

    public string HouseNo { get; set; }

    public string Createdby { get; set; }

    public string Modifiedby { get; set; }

    public Nullable<System.DateTime> DatetimeCreated { get; set; }

    public Nullable<System.DateTime> DatetimeUpdated { get; set; }



    public virtual Employee Employee { get; set; }

}

}
