
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Other
{

    public int OtherId { get; set; }

    public Nullable<int> UserId { get; set; }

    public Nullable<int> PensionSchemeId { get; set; }

    public string SalaryScale { get; set; }

    public string SalaryStep { get; set; }

    public string SalaryGradeLevel { get; set; }

    public Nullable<decimal> AnnualTransport { get; set; }

    public Nullable<decimal> AnnualBasicSalary { get; set; }

    public Nullable<decimal> AnnualRent { get; set; }

    public Nullable<decimal> AnnualOtherAllowances { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<System.DateTime> DatetimeCreated { get; set; }

    public Nullable<System.DateTime> DatetimeUpdated { get; set; }

}

}
