

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class PALSiteDBEntities : DbContext
{
    public PALSiteDBEntities()
        : base("name=PALSiteDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AccountManager> AccountManagers { get; set; }

    public virtual DbSet<AssetAllocation> AssetAllocations { get; set; }

    public virtual DbSet<AssetType> AssetTypes { get; set; }

    public virtual DbSet<BenefitApplication> BenefitApplications { get; set; }

    public virtual DbSet<BenefitClass> BenefitClasses { get; set; }

    public virtual DbSet<BenefitDocument> BenefitDocuments { get; set; }

    public virtual DbSet<BenefitSubClass> BenefitSubClasses { get; set; }

    public virtual DbSet<CaseSummary> CaseSummaries { get; set; }

    public virtual DbSet<ChangeOfAddressProfile> ChangeOfAddressProfiles { get; set; }

    public virtual DbSet<ChangeOfNameProfile> ChangeOfNameProfiles { get; set; }

    public virtual DbSet<ClientUpdate> ClientUpdates { get; set; }

    public virtual DbSet<Contribution> Contributions { get; set; }

    public virtual DbSet<EmployeeBenefitDocument> EmployeeBenefitDocuments { get; set; }

    public virtual DbSet<EmployerDetail> EmployerDetails { get; set; }

    public virtual DbSet<Publication> Publications { get; set; }

    public virtual DbSet<SecretQuestionsStore> SecretQuestionsStores { get; set; }

    public virtual DbSet<Sheme> Shemes { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    public virtual DbSet<SupportCategory> SupportCategories { get; set; }

    public virtual DbSet<SupportLog> SupportLogs { get; set; }

    public virtual DbSet<UploadType> UploadTypes { get; set; }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }

    public virtual DbSet<UserPublication> UserPublications { get; set; }

    public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }

    public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }

    public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }

    public virtual DbSet<PriceHistory> PriceHistories { get; set; }

    public virtual DbSet<ExitProcessMaster> ExitProcessMasters { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<ExpressionOfInterest> ExpressionOfInterests { get; set; }

    public virtual DbSet<NewExpressionOfInterest> NewExpressionOfInterests { get; set; }

    public virtual DbSet<BVNdata> BVNdatas { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<GradeLevel> GradeLevels { get; set; }

    public virtual DbSet<LGArea> LGAreas { get; set; }

    public virtual DbSet<MartialStatu> MartialStatus { get; set; }

    public virtual DbSet<Relationship> Relationships { get; set; }

    public virtual DbSet<SalaryStructure> SalaryStructures { get; set; }

    public virtual DbSet<Sector> Sectors { get; set; }

    public virtual DbSet<Sex> Sexes { get; set; }

    public virtual DbSet<StateOfOrigin> StateOfOrigins { get; set; }

    public virtual DbSet<StateOfPosting> StateOfPostings { get; set; }

    public virtual DbSet<Step> Steps { get; set; }

    public virtual DbSet<Title> Titles { get; set; }

    public virtual DbSet<State> States { get; set; }

    public virtual DbSet<EmployeeStatu> EmployeeStatus { get; set; }

    public virtual DbSet<ImageAdministration> ImageAdministrations { get; set; }

    public virtual DbSet<Other> Other { get; set; }

    public virtual DbSet<AgentType> AgentTypes { get; set; }

    public virtual DbSet<BenefitFile> BenefitFiles { get; set; }

    public virtual DbSet<BenefitProcess> BenefitProcesses { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Agent> Agents { get; set; }

    public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<BenefitChecklist> BenefitChecklists { get; set; }

    public virtual DbSet<BenefitChecklistMap> BenefitChecklistMaps { get; set; }

    public virtual DbSet<BenefitDifferential> BenefitDifferentials { get; set; }

    public virtual DbSet<BenefitRequirement> BenefitRequirements { get; set; }

    public virtual DbSet<BenefitStatu> BenefitStatus { get; set; }

    public virtual DbSet<BenefitStatusLog> BenefitStatusLogs { get; set; }

    public virtual DbSet<BirthDayLog> BirthDayLogs { get; set; }

    public virtual DbSet<Branding> Brandings { get; set; }

    public virtual DbSet<BusinessAssociate> BusinessAssociates { get; set; }

    public virtual DbSet<Campaign> Campaigns { get; set; }

    public virtual DbSet<Case> Cases { get; set; }

    public virtual DbSet<CaseAttachment> CaseAttachments { get; set; }

    public virtual DbSet<cnssl> cnssls { get; set; }

    public virtual DbSet<cnssl2> cnssl2 { get; set; }

    public virtual DbSet<Contact> Contacts { get; set; }

    public virtual DbSet<CONTRIBUTION_BATCH> CONTRIBUTION_BATCH { get; set; }

    public virtual DbSet<ContributionBatch> ContributionBatches { get; set; }

    public virtual DbSet<ContributionNotification> ContributionNotifications { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<ECRSResponse> ECRSResponses { get; set; }

    public virtual DbSet<EmailBatch> EmailBatches { get; set; }

    public virtual DbSet<EmailLog> EmailLogs { get; set; }

    public virtual DbSet<Emenite> Emenites { get; set; }

    public virtual DbSet<EmployeeBiometric> EmployeeBiometrics { get; set; }

    public virtual DbSet<EmployeeChildren> EmployeeChildrens { get; set; }

    public virtual DbSet<EmployeeClean> EmployeeCleans { get; set; }

    public virtual DbSet<EmployeeProfileUpdate> EmployeeProfileUpdates { get; set; }

    public virtual DbSet<EMP> EMPS { get; set; }

    public virtual DbSet<EnquiryLog> EnquiryLogs { get; set; }

    public virtual DbSet<FAQ> FAQs { get; set; }

    public virtual DbSet<Gender> Genders { get; set; }

    public virtual DbSet<GUIN> GUINs { get; set; }

    public virtual DbSet<HRCase> HRCases { get; set; }

    public virtual DbSet<Institution> Institutions { get; set; }

    public virtual DbSet<IssueCategory> IssueCategories { get; set; }

    public virtual DbSet<IssueOrigin> IssueOrigins { get; set; }

    public virtual DbSet<IssueType> IssueTypes { get; set; }

    public virtual DbSet<LGA> LGAs { get; set; }

    public virtual DbSet<LGA2> LGA2 { get; set; }

    public virtual DbSet<MCPPayment> MCPPayments { get; set; }

    public virtual DbSet<MobileShortCode> MobileShortCodes { get; set; }

    public virtual DbSet<NewEmployee> NewEmployees { get; set; }

    public virtual DbSet<NUPENG> NUPENGs { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Pfa> Pfas { get; set; }

    public virtual DbSet<RegDocument> RegDocuments { get; set; }

    public virtual DbSet<Region> Regions { get; set; }

    public virtual DbSet<RegOther> RegOthers { get; set; }

    public virtual DbSet<RegType> RegTypes { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ScheduleUpload> ScheduleUploads { get; set; }

    public virtual DbSet<ScheduleUploadTemp> ScheduleUploadTemps { get; set; }

    public virtual DbSet<StaffIdUpdate> StaffIdUpdates { get; set; }

    public virtual DbSet<State2> State2 { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<TestUser> TestUsers { get; set; }

    public virtual DbSet<UnProcessed> UnProcesseds { get; set; }

    public virtual DbSet<UserParameter> UserParameters { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<YouthLead> YouthLeads { get; set; }

    public virtual DbSet<CONTRI> CONTRIs { get; set; }

    public virtual DbSet<CONTRIBUTION1> CONTRIBUTIONs1 { get; set; }

    public virtual DbSet<ECRSContributor> ECRSContributors { get; set; }

    public virtual DbSet<Feedback_DEL> Feedback_DEL { get; set; }

    public virtual DbSet<Merchant> Merchants { get; set; }

    public virtual DbSet<SCHEDULE> SCHEDULES { get; set; }

    public virtual DbSet<testTable> testTables { get; set; }

    public virtual DbSet<ECRSPrivatePublicSector> ECRSPrivatePublicSectors { get; set; }

    public virtual DbSet<CFIBiometric> CFIBiometrics { get; set; }

    public virtual DbSet<CFINextOfKin> CFINextOfKins { get; set; }

    public virtual DbSet<CFIPublicPrivateSector> CFIPublicPrivateSectors { get; set; }

    public virtual DbSet<CFIRegisterUser> CFIRegisterUsers { get; set; }

    public virtual DbSet<CFISalaryStructure> CFISalaryStructures { get; set; }

    public virtual DbSet<CFISupportDocument> CFISupportDocuments { get; set; }

    public virtual DbSet<CFIOther> CFIOthers { get; set; }

    public virtual DbSet<CFIDocument> CFIDocuments { get; set; }

    public virtual DbSet<DigitalSubscription> DigitalSubscriptions { get; set; }

    public virtual DbSet<CFIEmploymentDetail> CFIEmploymentDetails { get; set; }

    public virtual DbSet<EmailRepository> EmailRepositories { get; set; }

    public virtual DbSet<PrivacySetting> PrivacySettings { get; set; }

    public virtual DbSet<NextOfKin> NextOfKins { get; set; }

    public virtual DbSet<SupportType> SupportTypes { get; set; }

    public virtual DbSet<Registration> Registrations { get; set; }

    public virtual DbSet<RegBiometric> RegBiometrics { get; set; }

    public virtual DbSet<Token> Tokens { get; set; }

    public virtual DbSet<LoginTrail> LoginTrails { get; set; }

    public virtual DbSet<TempCustomerInformation> TempCustomerInformations { get; set; }

    public virtual DbSet<TempNOKInformation> TempNOKInformations { get; set; }


    [DbFunction("PALSiteDBEntities", "GetContributionAggregate")]
    public virtual IQueryable<GetContributionAggregate_Result> GetContributionAggregate(string pin)
    {

        var pinParameter = pin != null ?
            new ObjectParameter("pin", pin) :
            new ObjectParameter("pin", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetContributionAggregate_Result>("[PALSiteDBEntities].[GetContributionAggregate](@pin)", pinParameter);
    }

}

}

