
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class PriceHistory
{

    public int price_history_id { get; set; }

    public Nullable<double> scheme_id { get; set; }

    public Nullable<System.DateTime> valuation_date { get; set; }

    public Nullable<decimal> bid_price { get; set; }

    public Nullable<decimal> offer_price { get; set; }

    public Nullable<decimal> Id { get; set; }

}

}
