
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class PrivacySetting
{

    public int Id { get; set; }

    public string Pin { get; set; }

    public string UserId { get; set; }

    public Nullable<bool> AcceptCookies { get; set; }

    public Nullable<System.DateTime> DateAccepted { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

}

}
