
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class RegBiometric
{

    public int RegBiometricId { get; set; }

    public int UserId { get; set; }

    public string Passport { get; set; }

    public string ContributorSignature { get; set; }

    public string ConsentForm { get; set; }

    public string PFASignature { get; set; }

    public bool Active { get; set; }

    public System.DateTime DatetimeCreated { get; set; }

    public System.DateTime DatetimeUpdated { get; set; }

    public bool ConsentAccepted { get; set; }



    public virtual Registration Registration { get; set; }

}

}
