
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Registration
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Registration()
    {

        this.RegOthers = new HashSet<RegOther>();

    }


    public int UserId { get; set; }

    public Nullable<int> RegTypeId { get; set; }

    public string FormRefNo { get; set; }

    public string Pin { get; set; }

    public string TPin { get; set; }

    public string PFAName { get; set; }

    public string BVN { get; set; }

    public string NIN { get; set; }

    public string IPN { get; set; }

    public Nullable<int> TitleId { get; set; }

    public string Surname { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string MaidenName { get; set; }

    public Nullable<int> EmployeeStatusId { get; set; }

    public Nullable<int> MaritalStatusId { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public Nullable<int> GenderId { get; set; }

    public Nullable<int> NationalityId { get; set; }

    public Nullable<int> PersonalStateOfOriginId { get; set; }

    public Nullable<int> LGAId { get; set; }

    public string City { get; set; }

    public string Mobile { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Email2 { get; set; }

    public string MotherMaidenName { get; set; }

    public string PlaceOfBirth { get; set; }

    public Nullable<bool> IsNigerian { get; set; }

    public string HouseNo { get; set; }

    public string StreetName { get; set; }

    public string LGACode { get; set; }

    public string StateCode { get; set; }

    public string CountryCode { get; set; }

    public Nullable<int> CountryOfResidanceId { get; set; }

    public string ZIP { get; set; }

    public string POBox { get; set; }

    public System.DateTime DatetimeCreated { get; set; }

    public Nullable<System.DateTime> DatetimeUpdated { get; set; }

    public bool Active { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public string Workstation { get; set; }

    public Nullable<bool> Checked { get; set; }

    public Nullable<System.DateTime> DateChecked { get; set; }

    public bool SentToPencom { get; set; }

    public string CheckedBy { get; set; }

    public string AgentCode { get; set; }

    public Nullable<System.DateTime> UploadDate { get; set; }

    public Nullable<bool> SmsSent { get; set; }

    public Nullable<System.DateTime> SmsDateSent { get; set; }

    public string SetId { get; set; }

    public Nullable<int> Sn { get; set; }

    public string ResponseCode { get; set; }

    public string ResponseMessage { get; set; }

    public Nullable<bool> MobileVerified { get; set; }

    public Nullable<bool> EmailVerified { get; set; }

    public Nullable<System.DateTime> DateMobileVerified { get; set; }

    public Nullable<System.DateTime> DateEmailVerified { get; set; }

    public string RegSource { get; set; }



    public virtual Country Country { get; set; }

    public virtual Country Country1 { get; set; }

    public virtual MartialStatu MartialStatu { get; set; }

    public virtual Sex Sex { get; set; }

    public virtual StateOfOrigin StateOfOrigin { get; set; }

    public virtual Title Title { get; set; }

    public virtual RegType RegType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RegOther> RegOthers { get; set; }

    public virtual RegBiometric RegBiometric { get; set; }

}

}
