
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class SCHEDULE
{

    public decimal IDNO { get; set; }

    public string SCHEDULE_CODE { get; set; }

    public string EMPLOYER_CODE { get; set; }

    public System.DateTime VALUE_DATE { get; set; }

    public Nullable<decimal> VPOSTED_BY { get; set; }

    public string VPOSTED { get; set; }

    public string POSTED { get; set; }

    public Nullable<System.DateTime> VPOSTED_DATE { get; set; }

    public Nullable<decimal> POSTED_BY { get; set; }

    public Nullable<System.DateTime> POSTED_DATE { get; set; }

    public decimal AMOUNT { get; set; }

    public Nullable<decimal> AMOUNT_PROCESSED { get; set; }

    public Nullable<System.DateTime> PROCESSED_DATE { get; set; }

    public Nullable<decimal> PROCESSED_BY { get; set; }

    public string COMMENT { get; set; }

    public string DESCRIPTION { get; set; }

    public string PFC_CODE { get; set; }

    public Nullable<decimal> REFUND_AMT { get; set; }

    public Nullable<System.DateTime> TRANS_DATE { get; set; }

    public string CLEARED { get; set; }

    public Nullable<decimal> FUND_ID { get; set; }

    public Nullable<System.DateTime> BOOKING_DATE { get; set; }

    public Nullable<decimal> USERID { get; set; }

    public string CHECKED { get; set; }

    public Nullable<decimal> CHECKED_BY { get; set; }

    public Nullable<System.DateTime> CHECKED_DATE { get; set; }

    public Nullable<decimal> TEMP_IDNO { get; set; }

    public string SCHEDULE_STATUS { get; set; }

    public string RETURNED { get; set; }

    public Nullable<decimal> TRANSFERRED_AMT { get; set; }

    public string REVERSAL_POSTED { get; set; }

    public string VREVERSAL_POSTED { get; set; }

    public string REFNO { get; set; }

}

}
