
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Sheme
{

    public Nullable<double> SCHEME_ID { get; set; }

    public string SCHEME_NAME { get; set; }

    public Nullable<System.DateTime> REPORT_DATE { get; set; }

    public Nullable<double> OFFER_PRICE { get; set; }

    public Nullable<double> BID_PRICE { get; set; }

    public string OFFER_FOR { get; set; }

    public string BID_FOR { get; set; }

    public Nullable<double> TOTAL_UNITS { get; set; }

    public string TOTAL_RECEIVABLES { get; set; }

    public Nullable<double> NAV { get; set; }

    public Nullable<double> GAV { get; set; }

    public string PAY_COT { get; set; }

    public string COT_PERCENT { get; set; }

    public string CALC_INTEREST { get; set; }

    public string INTEREST_RATE { get; set; }

    public string SCHEME_LOGO { get; set; }

    public Nullable<System.DateTime> START_DATE { get; set; }

    public Nullable<System.DateTime> LAST_PROC_DATE { get; set; }

    public string UPDATE_SUCCESS { get; set; }

    public Nullable<double> ACCRUED_DIVIDEND { get; set; }

    public string ACCRUED_FEES { get; set; }

    public string PAID_FEES { get; set; }

    public string MANAGER_HEADER_PAGE { get; set; }

    public string MANAGER_FOOTER_PAGE { get; set; }

    public string PROMISE { get; set; }

    public string SCHEME_TYPE { get; set; }

    public Nullable<double> COMPANY_ID { get; set; }

    public string LAST_POSTED { get; set; }

    public string STAMP_DUTIES { get; set; }

    public string NSE_CSCS_FEES { get; set; }

    public string BROKERAGE_FEES { get; set; }

    public string SEC_FEES { get; set; }

    public string CODE { get; set; }

    public string MGMT_FEE_PAYABLE_PERC { get; set; }

    public string EXCESS_FEE_PAYABLE_PERC { get; set; }

    public string VAT_ON_EXCESS_FEE { get; set; }

    public string TRANS_FEE_PAYABLE_PERC { get; set; }

    public string PERCENTAGE_ABOVE { get; set; }

    public string FEE_TYPE { get; set; }

    public string CONTRACT_BEGINS { get; set; }

    public string CONTRACT_ENDS { get; set; }

    public string ACCOUNT_STATUS { get; set; }

    public string CSCS_CODE { get; set; }

    public string ACCOUNT_CODE { get; set; }

    public string TROI_CODE { get; set; }

    public Nullable<double> OPENING_NAV { get; set; }

    public string RATING_REQUIRMENT { get; set; }

    public string POINT_TO_NOTE { get; set; }

    public string INVEST_GUIDELINE { get; set; }

    public string STANDING_ORDERS { get; set; }

    public string REPORTING_FREQ { get; set; }

    public string AGREEMENT_EXPIRY { get; set; }

    public int SCHEME_TABLE_ID { get; set; }

}

}
