
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class SupportLog
{

    public int Id { get; set; }

    public string Pin { get; set; }

    public Nullable<int> CategoryId { get; set; }

    public string Summary { get; set; }

    public string Explanation { get; set; }

    public Nullable<System.DateTime> DateSubmitted { get; set; }

    public Nullable<bool> Resolved { get; set; }

    public Nullable<System.DateTime> DateResolved { get; set; }

    public string PALComment { get; set; }

    public string CategoryName { get; set; }

    public string IssueType { get; set; }

    public string SupportType { get; set; }

    public string StateCode { get; set; }



    public virtual SupportCategory SupportCategory { get; set; }

    public virtual Employee Employee { get; set; }

}

}
