
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class TempCustomerInformation
{

    public int id { get; set; }

    public string pin { get; set; }

    public string mobile_number { get; set; }

    public string email { get; set; }

    public string parmanent_address { get; set; }

    public string home_address { get; set; }

    public string mobile_number2 { get; set; }

    public Nullable<System.DateTime> date_created { get; set; }

    public string name { get; set; }

    public string status { get; set; }

    public string MaritalStatusCode { get; set; }

    public string EmployerCode { get; set; }

    public string EmployerName { get; set; }

    public string Bvn { get; set; }

    public string Nin { get; set; }

    public Nullable<bool> IsNigerian { get; set; }

    public string HouseNo { get; set; }

    public string StreetName { get; set; }

    public string LGACode { get; set; }

    public string StateCode { get; set; }

    public string CountryCode { get; set; }

    public Nullable<bool> Processed { get; set; }

    public Nullable<System.DateTime> DateProcessed { get; set; }

    public Nullable<bool> Checked { get; set; }

    public Nullable<System.DateTime> DateChecked { get; set; }

    public string CheckedBy { get; set; }

    public string City { get; set; }

    public string Createdby { get; set; }

    public string Portal { get; set; }

    public Nullable<int> CountryOfResidanceId { get; set; }

}

}
