
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class TempNOKInformation
{

    public int id { get; set; }

    public string pin { get; set; }

    public string Surname { get; set; }

    public string FirstName { get; set; }

    public string OtherNames { get; set; }

    public Nullable<int> Gender { get; set; }

    public string KinTitle { get; set; }

    public string Relation { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string StateCode { get; set; }

    public string CountryCode { get; set; }

    public string City { get; set; }

    public string LGACode { get; set; }

    public string StreetName { get; set; }

    public string HouseNo { get; set; }

    public string status { get; set; }

    public Nullable<bool> Checked { get; set; }

    public string CheckedBy { get; set; }

    public Nullable<System.DateTime> DateChecked { get; set; }

    public Nullable<bool> Processed { get; set; }

    public Nullable<System.DateTime> DateProcessed { get; set; }

    public string Createdby { get; set; }

    public string Modifiedby { get; set; }

    public Nullable<System.DateTime> DatetimeCreated { get; set; }

    public Nullable<System.DateTime> DatetimeUpdated { get; set; }

    public string Portal { get; set; }

}

}
