
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class TestUser
{

    public int Id { get; set; }

    public string Pin { get; set; }

    public string Surname { get; set; }

    public string Firstname { get; set; }

    public string Email { get; set; }

    public string MobileNo { get; set; }

    public Nullable<decimal> EmployeeContribution { get; set; }

    public Nullable<decimal> EmployerContribution { get; set; }

    public Nullable<decimal> VoluntaryContribution { get; set; }

    public Nullable<int> FundId { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime DateCreated { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

}

}
