
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class UserParameter
{

    public int Id { get; set; }

    public string PName { get; set; }

    public string PValue { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public System.DateTime DatetimeCreated { get; set; }

    public Nullable<System.DateTime> DatetimeUpdated { get; set; }

}

}
