
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class UserPublication
{

    public int UserPublicationsId { get; set; }

    public Nullable<int> PublicationsId { get; set; }

    public string EmployeePin { get; set; }



    public virtual Publication Publication { get; set; }

    public virtual Employee Employee { get; set; }

}

}
