
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class UserProfile
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserProfile()
    {

        this.webpages_Roles = new HashSet<webpages_Roles>();

    }


    public int UserId { get; set; }

    public string UserName { get; set; }

    public Nullable<int> SecretQuestionId { get; set; }

    public string SecretQuestionAnswer { get; set; }

    public string VerificationCode { get; set; }

    public string Email { get; set; }

    public Nullable<int> InvestorId { get; set; }

    public string Employee_Pin { get; set; }

    public Nullable<System.DateTime> LastLogin { get; set; }

    public string QuestionKey { get; set; }

    public bool FirstSignOn { get; set; }

    public string AdminName { get; set; }

    public bool IsDisabled { get; set; }

    public Nullable<bool> EmailSent { get; set; }

    public string FullName { get; set; }

    public Nullable<System.DateTime> DatePwChanged { get; set; }

    public Nullable<bool> PasswordExpired { get; set; }

    public Nullable<System.DateTime> DatePwExpired { get; set; }



    public virtual SecretQuestionsStore SecretQuestionsStore { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }

}

}
