
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PalRSA.Core.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class YouthLead
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Surname { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string Gender { get; set; }

    public string MaritalStatus { get; set; }

    public System.DateTime DOB { get; set; }

    public Nullable<int> ExpectedGradYear { get; set; }

    public string MobilePhone { get; set; }

    public string Email { get; set; }

    public string HomeAddress { get; set; }

    public string StateOfOrigin { get; set; }

    public string LGACode { get; set; }

    public string AreaOfInterest { get; set; }

    public string Institution { get; set; }

    public string FacebookHandle { get; set; }

    public string InstagramHandle { get; set; }

    public string TwiterHandle { get; set; }

    public string LinkedInHandle { get; set; }

    public string ContactPrefered { get; set; }

    public System.DateTime DateCreated { get; set; }

}

}
